spring:
  application:
    name: api-gateway
server:
  port: 8080
zuul:
  routes:
    auth:
      path: /uaa/**
      url: http://127.0.0.1:8079
    backend:
      path: /backend/**
      url: http://127.0.0.1:8081
    backend2:
      path: /backend2/**
      url: http://127.0.0.1:8082
  sensitive-headers: # Keep blank value to allow all sensitive headers
logging:
  level:
    com.github.jccode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.springframework.cloud.netflix: trace

oauth2-header-filter:
  ignore-paths: /uaa/**
