server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: d:/temp/springcloud-centralized-config-git

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/discoveryserver/