package com.github.jccode.springcloud.integrateddemo.membership.repo;

import com.github.jccode.springbootsample.core.repo.CrudMapper;
import com.github.jccode.springcloud.integrateddemo.membership.model.MemberPointFlow;
import com.github.jccode.springcloud.integrateddemo.membership.model.MemberPointFlowCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberPointFlowMapper extends com.github.jccode.springbootsample.core.repo.CrudMapper<MemberPointFlow> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    long countByExample(MemberPointFlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int deleteByExample(MemberPointFlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int insert(MemberPointFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int insertSelective(MemberPointFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    List<MemberPointFlow> selectByExampleWithRowbounds(MemberPointFlowCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    List<MemberPointFlow> selectByExample(MemberPointFlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    MemberPointFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberPointFlow record, @Param("example") MemberPointFlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberPointFlow record, @Param("example") MemberPointFlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberPointFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINT_FLOW
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberPointFlow record);
}