spring:
  application:
    name: mdc-demo
logging:
  level: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(-%5p) %clr(){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(tx.id=%2X{transaction.id} tx.owner=%-8.8X{transaction.owner}){blue} %clr(:){faint} %m%n"
