
CREATE TABLE event_pub (
  id   INTEGER IDENTITY PRIMARY KEY,

  uuid VARCHAR(64) NOT NULL ,
  type VARCHAR(61) NOT NULL ,
  payload VARCHAR(1024) NOT NULL ,
  status INTEGER NOT NULL ,
  lock INTEGER NOT NULL ,

  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE event_sub (
  id   INTEGER IDENTITY PRIMARY KEY,

  uuid VARCHAR(64) NOT NULL ,
  type VARCHAR(61) NOT NULL ,
  payload VARCHAR(1024) NOT NULL ,
  status INTEGER NOT NULL ,
  lock INTEGER NOT NULL ,

  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
