package com.github.jccode.springcloud.integrateddemo.membership.repo;

import com.github.jccode.springbootsample.core.repo.CrudMapper;
import com.github.jccode.springcloud.integrateddemo.membership.model.MemberPoints;
import com.github.jccode.springcloud.integrateddemo.membership.model.MemberPointsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberPointsMapper extends com.github.jccode.springbootsample.core.repo.CrudMapper<MemberPoints> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    long countByExample(MemberPointsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int deleteByExample(MemberPointsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int insert(MemberPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int insertSelective(MemberPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    List<MemberPoints> selectByExampleWithRowbounds(MemberPointsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    List<MemberPoints> selectByExample(MemberPointsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    MemberPoints selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberPoints record, @Param("example") MemberPointsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberPoints record, @Param("example") MemberPointsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_POINTS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberPoints record);
}