spring:
  application:
    name: api-gateway
server:
  port: 8080
zuul:
  routes:
    auth:
      path: /auth/**
      url: http://127.0.0.1:8079
    backend:
      path: /backend/**
      url: http://127.0.0.1:8081
