spring:
  application:
    name: api-gateway
server:
  port: 8080
zuul:
  routes:
    auth:
      path: /auth/**
      url: http://127.0.0.1:8079
    backend:
      path: /backend/**
      url: http://127.0.0.1:8081
shiro:
  loginUrl: /auth/login
  unauthorizedUrl: /auth/unauthrized
logging:
  level:
    org.springframework.web: DEBUG
    org.apache.shiro: DEBUG
