DROP TABLE PRODUCT IF EXISTS ;

CREATE TABLE PRODUCT (
  id   INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  price INTEGER,
  stock INTEGER,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN PRODUCT.name IS '商品名';
COMMENT ON COLUMN PRODUCT.price IS '价格';
COMMENT ON COLUMN PRODUCT.stock IS '库存';

CREATE INDEX product_name ON PRODUCT (name);
