package com.github.jccode.springcloud.integrateddemo.common.event.repo;

import com.github.jccode.springbootsample.core.repo.CrudMapper;
import com.github.jccode.springcloud.integrateddemo.common.event.model.EventPub;
import com.github.jccode.springcloud.integrateddemo.common.event.model.EventPubCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EventPubMapper extends com.github.jccode.springbootsample.core.repo.CrudMapper<EventPub> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    long countByExample(EventPubCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int deleteByExample(EventPubCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int insert(EventPub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int insertSelective(EventPub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    List<EventPub> selectByExampleWithRowbounds(EventPubCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    List<EventPub> selectByExample(EventPubCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    EventPub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventPub record, @Param("example") EventPubCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventPub record, @Param("example") EventPubCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EventPub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_PUB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventPub record);
}