DROP TABLE account IF EXISTS ;

CREATE TABLE account (
  id   INTEGER IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL ,
  name VARCHAR(50) NOT NULL ,
  balance INTEGER,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- ALTER TABLE account ADD FOREIGN KEY (user_id) REFERENCES account(id);

CREATE INDEX account_name ON account (name);
