spring:
  application:
    name: rbac-guide
  datasource:
    url: jdbc:hsqldb:mem:mydb
    username: sa
    driver-class-name: org.hsqldb.jdbcDriver
    schema: classpath:db/hsqldb/schema.sql
    data: classpath:db/hsqldb/data.sql
logging:
  level:
    com.github.jccode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG
#security:
#  user:
#    name: tom
#    password: cat
