spring:
  application:
    name: rbac-guide
logging:
  level:
    com.github.jccode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#security:
#  user:
#    name: tom
#    password: cat
