spring:
  application:
    name: oauth2-guide

logging:
  level:
    com.github.jccode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

security:
  user:
    name: tom
    password: cat
  oauth2:
    client:
      client-id: webapp
      client-secret: 123456
      scope: read,write,query,contact,email,all
