package com.github.jccode.springcloud.integrateddemo.order.repo;

import com.github.jccode.springbootsample.core.repo.CrudMapper;
import com.github.jccode.springcloud.integrateddemo.order.model.OrderItem;
import com.github.jccode.springcloud.integrateddemo.order.model.OrderItemCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderItemMapper extends com.github.jccode.springbootsample.core.repo.CrudMapper<OrderItem> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    long countByExample(OrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int deleteByExample(OrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    List<OrderItem> selectByExampleWithRowbounds(OrderItemCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    List<OrderItem> selectByExample(OrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItem record);
}